// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {steam} from '../models';

export function DisableSteamCEFDebugging():Promise<void>;

export function EnableSteamCEFDebugging():Promise<void>;

export function Start(arg1:context.Context,arg2:steam.ServiceOptions):Promise<void>;

export function Status():Promise<steam.Status>;

export function SteamCEFDebuggingEnabled():Promise<boolean>;
