// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {steam} from '../models';

export function EnableSteamCEFRemoteDebugging():Promise<void>;

export function Init():Promise<void>;

export function Run():Promise<void>;

export function Status():Promise<steam.Status>;
