// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {steam} from '../models';
import {common} from '../models';

export function DisableSteamCEFDebugging():Promise<void>;

export function EnableSteamCEFDebugging():Promise<void>;

export function Start(arg1:steam.ServiceOptions):Promise<void>;

export function Status():Promise<common.Status>;

export function SteamCEFDebuggingEnabled():Promise<boolean>;
