// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnableSteamCEFRemoteDebugging() {
  return window['go']['steam']['Service']['EnableSteamCEFRemoteDebugging']();
}

export function Init() {
  return window['go']['steam']['Service']['Init']();
}

export function Run() {
  return window['go']['steam']['Service']['Run']();
}

export function Status() {
  return window['go']['steam']['Service']['Status']();
}
