// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableSteamCEFDebugging() {
  return window['go']['steam']['Service']['DisableSteamCEFDebugging']();
}

export function EnableSteamCEFDebugging() {
  return window['go']['steam']['Service']['EnableSteamCEFDebugging']();
}

export function Start(arg1, arg2) {
  return window['go']['steam']['Service']['Start'](arg1, arg2);
}

export function Status() {
  return window['go']['steam']['Service']['Status']();
}

export function SteamCEFDebuggingEnabled() {
  return window['go']['steam']['Service']['SteamCEFDebuggingEnabled']();
}
