// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {user} from '../models';
import {gin} from '../models';
import {context} from '../models';

export function GetLoginInfo():Promise<user.LoginInfo>;

export function GetLoginInfoEndpoint():Promise<string>;

export function GetLoginInfoHandler():Promise<gin.HandlerFunc>;

export function SignIn():Promise<void>;

export function SignOut():Promise<void>;

export function SignOutEndpoint():Promise<string>;

export function SignOutHandler():Promise<gin.HandlerFunc>;

export function Start(arg1:context.Context):Promise<void>;

export function UpdateSessionEndpoint():Promise<string>;

export function UpdateSessionHandler():Promise<gin.HandlerFunc>;

export function UpgradePlanWithLicense(arg1:string):Promise<void>;
