// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLoginInfo() {
  return window['go']['user']['Service']['GetLoginInfo']();
}

export function GetLoginInfoEndpoint() {
  return window['go']['user']['Service']['GetLoginInfoEndpoint']();
}

export function GetLoginInfoHandler() {
  return window['go']['user']['Service']['GetLoginInfoHandler']();
}

export function SignIn() {
  return window['go']['user']['Service']['SignIn']();
}

export function SignOut() {
  return window['go']['user']['Service']['SignOut']();
}

export function SignOutEndpoint() {
  return window['go']['user']['Service']['SignOutEndpoint']();
}

export function SignOutHandler() {
  return window['go']['user']['Service']['SignOutHandler']();
}

export function Start(arg1) {
  return window['go']['user']['Service']['Start'](arg1);
}

export function UpdateSessionEndpoint() {
  return window['go']['user']['Service']['UpdateSessionEndpoint']();
}

export function UpdateSessionHandler() {
  return window['go']['user']['Service']['UpdateSessionHandler']();
}

export function UpgradePlanWithLicense(arg1) {
  return window['go']['user']['Service']['UpgradePlanWithLicense'](arg1);
}
