// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMachineInfo() {
  return window['go']['machine']['Service']['GetMachineInfo']();
}

export function OpenBrowser(arg1) {
  return window['go']['machine']['Service']['OpenBrowser'](arg1);
}

export function Start() {
  return window['go']['machine']['Service']['Start']();
}
