// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {machine} from '../models';
import {context} from '../models';

export function GetMachineInfo():Promise<machine.Info>;

export function Start(arg1:context.Context):Promise<void>;
