// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disable() {
  return window['go']['startup']['Service']['Disable']();
}

export function Enable() {
  return window['go']['startup']['Service']['Enable']();
}

export function Enabled() {
  return window['go']['startup']['Service']['Enabled']();
}
