# 获取最终版本
POST https://joincyfzsuvolyklirho.supabase.co/functions/v1/version/latest/meta/windows-amd64.json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaW5jeWZ6c3V2b2x5a2xpcmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODc2MjMsImV4cCI6MjA1NjU2MzYyM30.1MOumBy-Hatxd25iynOUJh2ggIWdZMEzQeUfzV1fsZE
Content-Type: application/json
X-Meta-Channel: Develop

{
  "deviceId": "abc",
  "currentVersion": "0.0.7"
}
