// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setting} from '../models';

export function AutoRunDisable():Promise<void>;

export function AutoRunEnable():Promise<void>;

export function AutoRunEnabled():Promise<boolean>;

export function GetSetting():Promise<setting.Setting>;

export function SupportedLanguageLabels():Promise<Array<setting.LanguageLabel>>;

export function UpdateSetting(arg1:setting.Setting):Promise<void>;
