// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoRunDisable() {
  return window['go']['setting']['Service']['AutoRunDisable']();
}

export function AutoRunEnable() {
  return window['go']['setting']['Service']['AutoRunEnable']();
}

export function AutoRunEnabled() {
  return window['go']['setting']['Service']['AutoRunEnabled']();
}

export function GetSetting() {
  return window['go']['setting']['Service']['GetSetting']();
}

export function SupportedLanguageLabels() {
  return window['go']['setting']['Service']['SupportedLanguageLabels']();
}

export function UpdateSetting(arg1) {
  return window['go']['setting']['Service']['UpdateSetting'](arg1);
}
