
## 创建视频
### HTTP Create Videos
POST http://localhost:8081/api/records/v1alpha1/create
Content-Type: application/json

{
  "videoId": "test"
}



### HTTP Create Record
POST http://localhost:18012/api/records/v1alpha1/create
Content-Type: application/json

{

}

### HTTP List Record
POST http://localhost:18012/api/records/v1alpha1/list
Content-Type: application/json

{
  "path": "/Users/jiezi/tmp/hulu/guard/videos"
}

### GRPC List
GRPC grpc://localhost:18011/hulu.guard.api.records.v1alpha1.RecordService/List

{
  "path": "/Users/jiezi/tmp/hulu/guard/videos"
}